name: Node.js CI
on:
  workflow_dispatch:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Upload output filejson
        uses: actions/upload-artifact@v3
        with:
          name: testresultsjson
          path: /home/runner/work/ex14/ex14/reports/awesome-reports/mochawesome.json
      - name: Upload output filehtml
        uses: actions/upload-artifact@v3
        with:
          name: testresultshtml
          path: /home/runner/work/ex14/ex14/reports/awesome-reports/mochawesome.html
